// SPDX-License-Identifier: Apache-2.0

package hfdownloader

// The mount catalog is the read side of `hfdownloader mount`: a map from
// view-relative path ("ollama/blobs/sha256-..", "lmstudio/o/r/x.gguf") to
// either a backing file in the store or generated bytes (Ollama manifests and
// config blobs). It is rebuilt from the hub and local/ whenever they change.

import (
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// MountViews are the top-level directories of the mount.
var MountViews = []string{"ollama", "lmstudio", "hipfire", "maestro", "inbox"}

// MountOptions configures Mount.
type MountOptions struct {
	MountPoint   string // e.g. /srv/models/mnt
	UpperDir     string // writable layer, e.g. /srv/models/.upper
	DiffusionDir string // ComfyUI store; finished diffusion hub repos are sorted here
	AllowOther   bool   // let other users (system ollama) see the mount
	Debug        bool
	Watch        WatchOptions // ingest settings: Token, Endpoint, MaestroRepos, Settle, Log
}

type catEntry struct {
	Real  string // backing file (symlinks followed at stat/open time)
	Data  []byte // generated content (Real == "")
	MTime time.Time
}

type mountCatalog struct {
	files map[string]*catEntry
	dirs  map[string]map[string]bool // "" is the mount root
	stats map[string]int
}

func newMountCatalog() *mountCatalog {
	m := &mountCatalog{files: map[string]*catEntry{}, dirs: map[string]map[string]bool{"": {}}, stats: map[string]int{}}
	for _, v := range MountViews {
		m.dirs[""][v] = true
		m.dirs[v] = map[string]bool{}
	}
	return m
}

func (m *mountCatalog) add(rel string, e *catEntry) bool {
	if _, ok := m.files[rel]; ok {
		return false
	}
	m.files[rel] = e
	for child := rel; ; {
		d := path.Dir(child)
		if d == "." {
			d = ""
		}
		kids := m.dirs[d]
		if kids == nil {
			kids = map[string]bool{}
			m.dirs[d] = kids
		}
		kids[path.Base(child)] = true
		if d == "" {
			break
		}
		child = d
	}
	return true
}

func sortedRepos(files map[string][]HubFile) []string {
	out := make([]string, 0, len(files))
	for r := range files {
		out = append(out, r)
	}
	sort.Strings(out)
	return out
}

// buildMountCatalog lays hub and local files out the way each app expects.
// Hub entries win over local ones on a name clash.
func buildMountCatalog(hub, local map[string][]HubFile) *mountCatalog {
	m := newMountCatalog()
	now := time.Now()

	// Ollama: generated manifests + config blobs, layers are store files.
	for _, src := range []struct {
		host  string
		files map[string][]HubFile
	}{{"hf.co", hub}, {"local", local}} {
		for _, p := range planOllama(src.files, nil) {
			for _, l := range p.Layers {
				m.add("ollama/blobs/sha256-"+l.SHA, &catEntry{Real: l.Blob})
			}
			m.add("ollama/blobs/sha256-"+p.ConfigDigest, &catEntry{Data: p.Config, MTime: now})
			if m.add(path.Join("ollama/manifests", src.host, p.Repo, p.Tag), &catEntry{Data: p.Manifest, MTime: now}) {
				m.stats["ollama"]++
			}
		}
	}

	// LM Studio: <owner>/<repo>/<file>.gguf, flat per repo, no diffusion GGUFs.
	for _, files := range []map[string][]HubFile{hub, local} {
		for _, repo := range sortedRepos(files) {
			for _, f := range files[repo] {
				if !strings.HasSuffix(strings.ToLower(f.Path), ".gguf") {
					continue
				}
				if meta, err := readGGUFMetaCached(f.Blob); err == nil && diffusionArch[meta.Architecture] {
					continue
				}
				if m.add(path.Join("lmstudio", repo, path.Base(f.Path)), &catEntry{Real: f.Blob}) {
					m.stats["lmstudio"]++
				}
			}
		}
	}

	// hipfire: flat files of hipfire-models/* repos.
	for _, repo := range sortedRepos(hub) {
		if !strings.HasPrefix(repo, "hipfire-models/") {
			continue
		}
		for _, f := range hub[repo] {
			b := strings.ToLower(path.Base(f.Path))
			if b == "readme.md" || b == ".gitattributes" || strings.HasSuffix(b, ".json") {
				continue
			}
			if m.add(path.Join("hipfire", path.Base(f.Path)), &catEntry{Real: f.Blob}) {
				m.stats["hipfire"]++
			}
		}
	}
	return m
}

// localFiles lists <root>/local/<owner>/<repo>/** as pseudo-repos. sha maps
// absolute path -> sha256 for files already hashed (needed for Ollama digests).
func localFiles(root string, sha func(p string) string) map[string][]HubFile {
	base := filepath.Join(root, "local")
	out := map[string][]HubFile{}
	filepath.WalkDir(base, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if strings.HasPrefix(d.Name(), ".") && p != base {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			return nil
		}
		rel, _ := filepath.Rel(base, p)
		parts := strings.SplitN(filepath.ToSlash(rel), "/", 3)
		if len(parts) != 3 {
			return nil
		}
		fi, err := os.Stat(p)
		if err != nil || !fi.Mode().IsRegular() || fi.Size() == 0 {
			return nil
		}
		repo := parts[0] + "/" + parts[1]
		out[repo] = append(out[repo], HubFile{
			Repo: repo, Path: parts[2], Snapshot: p, Blob: p,
			SHA: sha(p), Size: fi.Size(), ModTime: fi.ModTime(),
		})
		return nil
	})
	return out
}
